[package]
name = "taskboard"
version = "0.1.0"
authors = ["sdn0303 <sdn03.tech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.17", package = "yew-stdweb" }
